# ref: http://eslint.org/docs/rules/
env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    SwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console:
    - off
